name: "test-action "
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  # test action works running from the graph
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: ./
